# permissions for end users to edit rekors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rekor-editor-role
rules:
- apiGroups:
  - helm.sigstore.dev
  resources:
  - rekors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.sigstore.dev
  resources:
  - rekors/status
  verbs:
  - get
