# permissions for end users to view rekors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rekor-viewer-role
rules:
- apiGroups:
  - helm.sigstore.dev
  resources:
  - rekors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helm.sigstore.dev
  resources:
  - rekors/status
  verbs:
  - get
