{{- if .Values.redis.enabled -}}
{{- if .Values.redis.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "rekor.redis.labels" . | nindent 4 }}
  name: {{ template "rekor.serviceAccountName.redis" . }}
{{ include "rekor.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.redis.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}

